(()=>{'use strict';
const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
let bound=false,history=[];
function fallback(text){const t=String(text||'').toLowerCase();if(/hello|hi|hey/.test(t))return 'Great! 👋 Kendini tanıtmayı dene: “My name is … and I am from Türkiye.”';if(/name/.test(t))return 'Nice to meet you! Şimdi yaşını ve ne yaptığını söyle: “I am … years old. I work at …”';if(/work|job/.test(t))return 'Very good! Bir doğal cümle daha: “I work at a factory.” Şimdi sen söyle.';if(/travel|trip/.test(t))return 'Nice topic! “I want to travel to …” cümlesini tamamlamayı dene.';return 'Good job! ✨ Cümleni biraz daha doğal yapalım. Bir ayrıntı ekleyip tekrar söyle.';}
async function ask(text){const box=$('#aiMessages');if(!box)return;history.push({role:'user',text});box.insertAdjacentHTML('beforeend',`<div class="ai-msg user">${esc(text)}</div>`);box.insertAdjacentHTML('beforeend','<div class="ai-msg tutor" id="aiThinking">Düşünüyorum…</div>');box.scrollTop=box.scrollHeight;try{const r=await fetch('/api/coach',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({prompt:'Have a short English conversation with the learner. Ask one question at a time. Correct only the most important mistake and encourage speaking.',transcript:text,level:localStorage.getItem('speakio_level')||'A1'})});const data=r.status===204?null:await r.json();const reply=data?.text||fallback(text);$('#aiThinking')?.remove();history.push({role:'assistant',text:reply});box.insertAdjacentHTML('beforeend',`<div class="ai-msg tutor">${esc(reply).replace(/\n/g,'<br>')}</div>`);box.scrollTop=box.scrollHeight;}catch(e){$('#aiThinking')?.remove();box.insertAdjacentHTML('beforeend',`<div class="ai-msg tutor">${esc(fallback(text))}</div>`);}}
function speakScreen(){const root=$('#app');if(!root||!root.querySelector('.practice'))return;if(root.dataset.aiTutor==='1')return;root.dataset.aiTutor='1';root.innerHTML=`<section class="ai-screen"><header><button onclick="Speakio.go('home')">‹</button><b>AI English Tutor</b><span></span></header><div class="ai-profile"><div class="ai-avatar">🤖</div><div><b>Speakio Coach</b><small>A1 • Friendly English teacher</small></div><span>● Online</span></div><div id="aiMessages" class="ai-messages"><div class="ai-msg tutor">Hi! 👋 Ben Speakio. İngilizce konuşma pratiği yapalım. What is your name?</div></div><div class="ai-task">🎯 <b>Görev:</b> Kısa cevap ver. Hata yaparsan birlikte düzelteceğiz.</div><div class="ai-compose"><input id="aiInput" class="input" placeholder="İngilizce yaz…" autocomplete="off"><button id="aiMic" class="ai-mic">🎙️</button><button id="aiSend" class="primary">Gönder</button></div><p class="muted center">Konuşabilir veya yazarak cevap verebilirsin.</p></section>`;$('#aiSend')?.addEventListener('click',()=>{const i=$('#aiInput');const v=i?.value.trim();if(v){i.value='';ask(v)}});$('#aiInput')?.addEventListener('keydown',e=>{if(e.key==='Enter')$('#aiSend')?.click()});$('#aiMic')?.addEventListener('click',()=>{const R=window.SpeechRecognition||window.webkitSpeechRecognition;if(!R){alert('Bu tarayıcı ses tanımayı desteklemiyor.');return}const r=new R();r.lang='en-US';r.interimResults=false;r.onresult=e=>{const v=e.results[0][0].transcript;const i=$('#aiInput');if(i)i.value=v};r.start()});}
function watch(){const o=new MutationObserver(()=>setTimeout(speakScreen,0));o.observe(document.documentElement,{childList:true,subtree:true});setTimeout(speakScreen,0)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',watch,{once:true});else watch();
})();
