(()=>{
'use strict';
const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const KEY='speakio_state_v2';
let state=JSON.parse(localStorage.getItem(KEY)||'null')||{name:'Ahmet',xp:1250,streak:7,goal:3,completed:[],savedWords:[],knownWords:[],sound:true,auto:true,first:true,week:[2,3,3,4,3,4,0],listeningDone:0,mistakes:[],review:{} };
let course=null, screen='home', lessonId=null, qi=0, score=0, selected=null, build=[], listenItem=null, speaking=null;
const save=()=>{localStorage.setItem(KEY,JSON.stringify(state));};
const units=()=>course?.units||[];
const unit=id=>units().find(u=>+u.id===+id);
const xp=n=>{state.xp+=n;save();toast('+'+n+' XP kazandın ✨');};
const toast=t=>{let e=$('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),1700)};
const go=s=>{screen=s;render();window.scrollTo(0,0)};
function nav(){return `<nav class="bottom"><button class="${screen==='home'?'active':''}" onclick="Speakio.go('home')">⌂<small>Ana Sayfa</small></button><button class="${['lessons','lesson','result'].includes(screen)?'active':''}" onclick="Speakio.go('lessons')">◎<small>Dersler</small></button><button class="${screen==='speak'?'active':''}" onclick="Speakio.go('speak')">◉<small>Konuş</small></button><button class="${['profile','settings'].includes(screen)?'active':''}" onclick="Speakio.go('profile')">◌<small>Profil</small></button></nav>`}
function top(title,back='home'){return `<header><button onclick="Speakio.go('${back}')">‹</button><b>${esc(title)}</b><span></span></header>`}
function stats(){return `<div class="stats"><div><strong>🔥 ${state.streak}</strong><small>Gün seri</small></div><div><strong>⚡ ${state.xp}</strong><small>XP</small></div><div><strong>🎯 ${state.goal}</strong><small>Günlük hedef</small></div></div>`}
function home(){let done=state.completed.length,total=units().length, pct=total?Math.round(done/total*100):0;return `<section><div class="hero"><div><small>Tekrar hoş geldin</small><h1>${esc(state.name)} 👋</h1><p>Bugün İngilizce konuşmaya hazır mısın?</p></div><div class="avatar">${esc((state.name||'S').slice(0,1).toUpperCase())}</div></div>${stats()}<div class="card"><div class="row"><b>🎯 A1 Yolculuğun</b><span>${done}/${total}</span></div><div class="progress"><i style="width:${pct}%"></i></div><small>${pct}% tamamlandı • Hedef: günlük ${state.goal} ders</small></div><div class="section"><b>Bugünün dersi</b><button onclick="Speakio.go('lessons')">Tümünü gör ›</button></div>${lessonCard(units().find(u=>!state.completed.includes(+u.id))||units()[0])}<div class="section"><b>Hızlı pratik</b></div><div class="grid"><button class="tile" onclick="Speakio.go('speak')">🎙️<b>AI Speak</b><small>Konuşma pratiği</small></button><button class="tile" onclick="Speakio.go('words')">📚<b>Kelimeler</b><small>Tekrar yap</small></button><button class="tile" onclick="Speakio.go('listen')">🎧<b>Dinleme</b><small>Kulağını geliştir</small></button><button class="tile" onclick="Speakio.go('grammar')">🧩<b>Dilbilgisi</b><small>A1 temelleri</small></button></div></section>`}
function lessonCard(u){if(!u)return '';let done=state.completed.includes(+u.id);return `<button class="lesson" onclick="Speakio.startLesson(${u.id})"><span class="node ${done?'done':''}">${done?'✓':'▶'}</span><span><b>${esc(u.title)}</b><small>${esc(u.learningObjective||'Günlük iletişim pratiği')}</small></span><em>${done?'Tamamlandı':'Başla'}</em></button>`}
function lessons(){return `<section>${top('A1 Kursu')}<div class="courseHead"><b>İngilizce A1</b><span>${state.completed.length}/${units().length}</span></div><p class="muted">Temelden günlük konuşmaya: kelime → dilbilgisi → cümle → dinleme → konuşma.</p><div class="map">${units().map((u,i)=>`<div class="maprow"><span class="node ${state.completed.includes(+u.id)?'done':''}">${state.completed.includes(+u.id)?'✓':i+1}</span><div>${lessonCard(u)}</div></div>`).join('')}</div></section>`}
function startLesson(id){lessonId=+id;qi=0;score=0;selected=null;build=[];go('lesson')}
function exercise(){let ex=unit(lessonId)?.exercises||[];return ex[qi%ex.length]}
function lesson(){let u=unit(lessonId), ex=exercise();if(!u||!ex)return lessons();let type=ex.type||'mcq';let body='';if(type==='mcq'){body=`<div class="answers">${(ex.options||[]).map((o,i)=>`<button class="answer" onclick="Speakio.answer(${i})">${esc(o)}</button>`).join('')}</div>`}else if(type==='translate'){body=`<input id="answer" class="input" placeholder="İngilizce yaz..." autocomplete="off"><button class="primary full" onclick="Speakio.checkText()">Kontrol et</button>`}else if(type==='build'){let words=(ex.words||ex.answer?.split(' ')||[]);body=`<div class="build">${build.map(w=>`<span>${esc(w)}</span>`).join(' ')}</div><div class="answers">${words.filter((w,i)=>!build.includes(w)).map(w=>`<button class="answer" onclick="Speakio.addWord('${esc(w)}')">${esc(w)}</button>`).join('')}</div><button class="primary full" onclick="Speakio.checkBuild()">Cevabı kontrol et</button>`}else body=`<div class="phrase">${esc(ex.prompt||ex.question||'')}</div><button class="primary full" onclick="Speakio.next(true)">Devam</button>`;return `<section>${top(u.title,'lessons')}<div class="lessonMeta"><span>Ders ${qi+1}/${u.exercises.length}</span><span>${score} doğru</span></div><div class="progress"><i style="width:${Math.round((qi/u.exercises.length)*100)}%"></i></div><div class="lessonbox"><span class="pill">${esc(type.toUpperCase())}</span><h2>${esc(ex.question||ex.prompt||ex.tr||u.title)}</h2>${ex.context?`<p class="muted">${esc(ex.context)}</p>`:''}${body}</div>${u.grammar?`<div class="hint">💡 ${esc(u.grammar)}</div>`:''}</section>`}
function norm(s){return String(s).toLowerCase().trim().replace(/[.,!?;:'"“”‘’]/g,'').replace(/\s+/g,' ')}
function answer(i){let ex=exercise(), ok=norm(ex.options?.[i])===norm(ex.answer);finishAnswer(ok,ex)}
function checkText(){let ex=exercise(),v=$('#answer')?.value||'';let answers=Array.isArray(ex.answers)?ex.answers:[ex.answer];let ok=answers.some(a=>norm(a)===norm(v));finishAnswer(ok,ex)}
function addWord(w){build.push(w);render()}
function checkBuild(){let ex=exercise(), expected=ex.answer||'';finishAnswer(norm(build.join(' '))===norm(expected),ex);build=[]}
function finishAnswer(ok,ex){if(ok){score++;}else{state.mistakes.push({unitId:lessonId,question:ex.question||ex.prompt||'',answer:ex.answer||''});save()}toast(ok?'Doğru! 🎉':'Tekrar deneyelim 💪');setTimeout(()=>next(ok),450)}
function next(ok){qi++;if(qi>=(unit(lessonId)?.exercises?.length||1)){if(!state.completed.includes(+lessonId)){state.completed.push(+lessonId);save();xp(25)}screen='result';render()}else{selected=null;build=[];render()}}
function result(){let u=unit(lessonId);return `<section>${top('Ders tamamlandı','lessons')}<div class="resultHero">🎉<h1>Harika iş!</h1><p>${esc(u?.title||'Ders')} tamamlandı.</p></div><div class="stats"><div><strong>${score}</strong><small>Doğru</small></div><div><strong>${u?.exercises?.length||0}</strong><small>Soru</small></div><div><strong>+25</strong><small>XP</small></div></div><button class="primary full" onclick="Speakio.go('lessons')">Kursa devam et</button><button class="secondary full" onclick="Speakio.startLesson(${lessonId})">Tekrar çöz</button></section>`}
function words(){let all=(typeof getSpeakioVocabulary==='function'?getSpeakioVocabulary():[]);if(!all.length)return `<section>${top('Kelimeler')}<div class="empty">İçerik yükleniyor…</div></section>`;let v=all[Math.min(state.savedWords.length,all.length-1)]||all[0];return `<section>${top('Kelimeler')}<div class="word"><div class="wordemoji">🗣️</div><h2>${esc(v.en)}</h2><span class="pron">A1 • ${esc(v.unit)}</span><p>${esc(v.tr)}</p><button class="audio" onclick="Speakio.say('${esc(v.en)}')">🔊</button></div><div class="wordactions"><button onclick="Speakio.saveWord(${v.unitId},'${esc(v.en)}')">🔖</button><button onclick="Speakio.nextWord()">→</button></div><div class="card"><b>Örnek kullanım</b><p class="muted">${esc(unit(v.unitId)?.targetSentences?.[0]||'')}</p></div></section>`}
function saveWord(id,w){if(!state.savedWords.includes(w))state.savedWords.push(w);save();toast('Kelime kaydedildi 🔖');}
function nextWord(){state.savedWords.push('_');save();render()}
function listen(){let arr=typeof getSpeakioListening==='function'?getSpeakioListening():[];if(!arr.length)return `<section>${top('Dinleme')}<div class="empty">İçerik yükleniyor…</div></section>`;listenItem=listenItem||arr[Math.floor(Math.random()*arr.length)];let opts=[listenItem.text,...arr.filter(x=>x.text!==listenItem.text).sort(()=>Math.random()-.5).slice(0,3).map(x=>x.text)].sort(()=>Math.random()-.5);return `<section>${top('Dinleme')}<div class="listen"><span class="pill">${esc(listenItem.unit)}</span><h2>Ne duydun?</h2><button class="audio" onclick="Speakio.say('${esc(listenItem.text)}')">🔊</button>${opts.map(o=>`<button class="choice" onclick="Speakio.listenAnswer(this,'${esc(o)}')">${esc(o)}</button>`).join('')}</div></section>`}
function listenAnswer(el,v){let ok=norm(v)===norm(listenItem.text);el.classList.add(ok?'selected':'wrong');if(ok){state.listeningDone++;save();xp(10)}else toast('Bir kez daha dinle 🎧');listenItem=null;setTimeout(render,700)}
function speak(){let tasks=typeof getSpeakioSpeaking==='function'?getSpeakioSpeaking():[];let t=tasks[(state.conversations||0)%Math.max(tasks.length,1)]||{prompt:'Introduce yourself in English.'};return `<section>${top('AI Speak')}<div class="practice"><div class="coach">🤖</div><div class="bubble"><b>Görev</b><br>${esc(t.prompt)}</div></div><button id="mic" class="mic" onclick="Speakio.listenSpeech()">🎙️</button><p class="center muted">Mikrofona dokun ve İngilizce konuş.</p><div class="card"><b>Örnek</b><p>${esc(unit(lessonId||1)?.targetSentences?.[0]||'Hello, my name is Ahmet.')}</p><button class="link" onclick="Speakio.say('${esc(unit(lessonId||1)?.targetSentences?.[0]||'Hello, my name is Ahmet.')}')">🔊 Dinle</button></div></section>`}
function listenSpeech(){let Speech=window.SpeechRecognition||window.webkitSpeechRecognition;if(!Speech){toast('Tarayıcın ses tanımayı desteklemiyor.');return}let r=new Speech();r.lang='en-US';r.interimResults=false;r.onstart=()=>$('#mic')?.classList.add('listening');r.onend=()=>$('#mic')?.classList.remove('listening');r.onerror=()=>toast('Mikrofon izni veya bağlantıyı kontrol et.');r.onresult=e=>{let text=e.results[0][0].transcript;state.conversations=(state.conversations||0)+1;save();toast('Duydum: '+text);setTimeout(()=>{alert('Atlas değil, Speakio Coach: “Good job! Şimdi cümleyi biraz daha uzun kurmayı dene.”');},100)};r.start()}
function grammar(){let u=units()[0]||{};return `<section>${top('Dilbilgisi')}<div class="card"><span class="pill">A1</span><h2>Temel İngilizce</h2><p>${esc(u.grammar||'am / is / are, temel soru kalıpları ve günlük cümleler')}</p></div>${units().slice(0,8).map(x=>`<div class="profileline"><b>${esc(x.title)}</b><small>${esc(x.grammar||'Temel yapı')}</small></div>`).join('')}</section>`}
function profile(){return `<section>${top('Profil')}<div class="profilehead"><div class="bigavatar">${esc((state.name||'S').slice(0,1).toUpperCase())}</div><div><h2>${esc(state.name)}</h2><span class="level">A1 • ${state.xp} XP</span></div></div>${stats()}<div class="profileline" onclick="Speakio.go('achievements')"><b>🏆 Başarımlar</b><span>›</span></div><div class="profileline" onclick="Speakio.go('settings')"><b>⚙️ Ayarlar</b><span>›</span></div></section>`}
function achievements(){let items=[['🔥','7 Gün Serisi',state.streak>=7],['⚡','1000 XP',state.xp>=1000],['📚','İlk Ders',state.completed.length>=1],['🎧','Dinleme',state.listeningDone>=3],['🗣️','Konuşma',state.conversations>=5],['🏆','A1 Ustası',state.completed.length>=units().length]];return `<section>${top('Başarımlar')}<div class="achgrid">${items.map(x=>`<div class="achievement ${x[2]?'':'locked'}"><span>${x[0]}</span><b>${x[1]}</b><small>${x[2]?'Kazanıldı':'Kilitli'}</small></div>`).join('')}</div></section>`}
function settings(){return `<section>${top('Ayarlar')}<div class="setting"><b>Ses efektleri</b><button class="toggle ${state.sound?'on':''}" onclick="Speakio.toggle('sound')"></button></div><div class="setting"><b>Otomatik ses</b><button class="toggle ${state.auto?'on':''}" onclick="Speakio.toggle('auto')"></button></div><div class="card"><b>Profil adı</b><input class="input" value="${esc(state.name)}" onchange="Speakio.rename(this.value)"></div><button class="danger full" onclick="Speakio.reset()">İlerlemeyi sıfırla</button></section>`}
function render(){let content=screen==='home'?home():screen==='lessons'?lessons():screen==='lesson'?lesson():screen==='result'?result():screen==='words'?words():screen==='listen'?listen():screen==='speak'?speak():screen==='grammar'?grammar():screen==='profile'?profile():screen==='achievements'?achievements():settings();$('#app').innerHTML=`<main>${content}</main>${['home','lessons','speak','profile'].includes(screen)?nav():''}<div id="toast" class="toast"></div>`}
function say(t){if(!('speechSynthesis'in window))return;let u=new SpeechSynthesisUtterance(t);u.lang='en-US';speechSynthesis.cancel();speechSynthesis.speak(u)}
function boot(){course=window.SpeakioContent?.course||null;if(!course){window.addEventListener('speakio:content-ready',e=>{course=e.detail;render()},{once:true})}render()}
window.Speakio={go,startLesson,answer,checkText,addWord,checkBuild,next,saveWord,nextWord,say,listenAnswer,listenSpeech,toggle:k=>{state[k]=!state[k];save();render()},rename:v=>{state.name=v||'Öğrenci';save();render()},reset:()=>{if(confirm('Tüm ilerleme silinsin mi?')){localStorage.removeItem(KEY);location.reload()}}};
boot();
})();