(()=>{'use strict';
const KEY='speakio_state_v3';
const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const FALLBACK={level:'A1',title:'İngilizce A1',description:'Günlük hayatta temel İngilizce iletişim için 12 üniteli başlangıç kursu.',units:[['Selamlaşma ve Tanışma','Selamlaşmak, vedalaşmak ve kendini tanıtmak.','👋'],['Kendini Tanıtma','Ülke, şehir, yaş ve kişisel bilgiler hakkında konuşmak.','🙋'],['Sayılar, Saat ve Yaş','Sayıları, fiyatları, yaşı ve saati kullanmak.','🔢'],['Aile ve İnsanlar','Aile üyelerini tanıtmak ve sahiplik bildirmek.','👨‍👩‍👧'],['Yiyecek ve İçecek','Yemek sipariş etmek ve istek belirtmek.','🍽️'],['Ev ve Eşyalar','Evdeki temel yerleri ve nesneleri tarif etmek.','🏠'],['Günlük Rutin','Günlük alışkanlıkları ve zaman sırasını anlatmak.','⏰'],['İş ve Meslek','İşini, görevlerini ve yardım taleplerini ifade etmek.','💼'],['Şehir ve Yönler','Yer sormak, yön tarif etmek ve mesafe belirtmek.','🧭'],['Alışveriş','Fiyat sormak, ürün istemek ve ödeme yapmak.','🛍️'],['Seyahat ve Otel','Bilet, otel ve ulaşım hakkında temel ihtiyaçları ifade etmek.','✈️'],['Geçmiş Zaman ve Tekrar','Geçmişte yapılan temel eylemleri anlatmak ve A1\'i tekrar etmek.','🔁']].map((x,i)=>({id:i+1,title:x[0],goal:x[1],emoji:x[2]}))};
let homeData=null;
const read=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'{}')}catch{return {}}};
const today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
function renderHome(){const s=read(),daily=s.daily?.date===today()?s.daily:{done:0},units=homeData?.units||[],done=Array.isArray(s.completed)?s.completed.map(Number):[],total=units.length,p=total?Math.round(done.length/total*100):0,cur=units.find(u=>!done.includes(+u.id))||units[0];const app=$('#app');if(!app)return;app.innerHTML=`<main><section><div class="hero"><div><small>Tekrar hoş geldin</small><h1>${esc(s.name||'Öğrenci')} 👋</h1><p>Bugün İngilizce konuşmaya hazır mısın?</p></div><div class="avatar">${esc((s.name||'S')[0].toUpperCase())}</div></div><div class="stats"><div><strong>🔥 ${Number(s.streak||0)}</strong><small>Gün seri</small></div><div><strong>⚡ ${Number(s.xp||0)}</strong><small>XP</small></div><div><strong>🎯 ${Number(s.goal||3)}</strong><small>Günlük hedef</small></div></div><div class="card"><div class="row"><b>🎯 A1 Yolculuğun</b><span>${done.length}/${total}</span></div><div class="progress"><i style="width:${p}%"></i></div><small>${p}% tamamlandı • Bugün ${Number(daily.done||0)}/${Number(s.goal||3)} hedef</small></div><div class="section"><b>Bugünün dersi</b><button onclick="Speakio.go('lessons')">Tümünü gör ›</button></div>${cur?`<button class="lesson" onclick="Speakio.startLesson(${cur.id})"><span class="node">▶</span><span><b>${esc(cur.emoji||'📘')} ${esc(cur.title)}</b><small>${esc(cur.goal)}</small></span><em>Başla</em></button>`:`<div class="card"><b>A1 tamamlandı 🎉</b><small>Tüm üniteleri tekrar edebilir veya konuşma pratiğine geçebilirsin.</small></div>`}<div class="section"><b>Hızlı pratik</b></div><div class="grid"><button class="tile" onclick="Speakio.go('speak')">🎙️<b>AI Speak</b><small>Konuşma pratiği</small></button><button class="tile" onclick="Speakio.go('review')">🧠<b>Tekrar</b><small>${Array.isArray(s.mistakes)?s.mistakes.length:0} zayıf soru</small></button><button class="tile" onclick="Speakio.go('listen')">🎧<b>Dinleme</b><small>${Number(s.listeningDone||0)} tamamlandı</small></button><button class="tile" onclick="Speakio.go('words')">📚<b>Kelimeler</b><small>${Array.isArray(s.savedWords)?s.savedWords.length:0} kayıtlı</small></button></div><button class="secondary full" onclick="Speakio.go('analytics')">📊 Öğrenme istatistiklerim</button></section></main><nav class="bottom"><button class="active" onclick="Speakio.go('home')">⌂<small>Ana Sayfa</small></button><button onclick="Speakio.go('lessons')">◎<small>Dersler</small></button><button onclick="Speakio.go('speak')">◉<small>Konuş</small></button><button onclick="Speakio.go('profile')">◌<small>Profil</small></button></nav>`}
async function loadHome(){try{const level=String(localStorage.getItem('speakio_level')||'A1').toUpperCase();const r=await fetch('./content/home.json?level='+encodeURIComponent(level)+'&v=2',{cache:'no-store'});if(!r.ok)throw new Error('Home HTTP '+r.status);const data=await r.json();if(!data||!Array.isArray(data.units)||!data.units.length)throw new Error('Home manifest invalid');homeData=data}catch(e){console.warn('Speakio home manifest fallback',e);homeData=FALLBACK}renderHome()}
window.SpeakioHome={render:renderHome,load:loadHome};
loadHome();
})();