import fs from 'node:fs';
import assert from 'node:assert/strict';
import { spawnSync } from 'node:child_process';
const syntaxOnly=process.argv.includes('--syntax-only');
const required=['index.html','app.js','runtime-fixes.js','build-fix.js','course-system.js','premium.js','premium-ui.js','sw.js','content/content-loader.js','content/a1-curriculum.json','content/a2-curriculum.json','api/coach.js'];
for(const file of required)assert.ok(fs.existsSync(file),`missing ${file}`);
for(const file of ['app.js','runtime-fixes.js','build-fix.js','course-system.js','premium.js','premium-ui.js','sw.js','content/content-loader.js']){const source=fs.readFileSync(file,'utf8');assert.ok(source.trim(),'empty '+file);try{new Function(source)}catch(error){throw new Error(`${file}: syntax error — ${error.message}`)}}
const moduleCheck=spawnSync(process.execPath,['--check','api/coach.js'],{encoding:'utf8'});assert.equal(moduleCheck.status,0,`api/coach.js: syntax error — ${moduleCheck.stderr}`);
if(syntaxOnly){console.log('Speakio syntax QA OK.');process.exit(0)}
const tokens=value=>String(value).toLowerCase().replace(/[.,!?;:'"“”‘’]/g,'').split(/\s+/).filter(Boolean).sort().join('|');
function validateCourse(file,level){const json=JSON.parse(fs.readFileSync(file,'utf8'));assert.equal(json.course.language,'English');assert.equal(json.course.nativeLanguage,'Turkish');assert.equal(json.course.level,level);assert.equal(json.course.id,`en-${level.toLowerCase()}`);assert.equal(json.units.length,12);assert.ok(json.review?.masteryTarget>=.8);const ids=new Set();for(const u of json.units){assert.ok(Number.isInteger(u.id)&&!ids.has(u.id),`${level}: duplicate/invalid unit ${u.id}`);ids.add(u.id);assert.ok(u.title&&u.goal&&u.grammar,`${level} unit ${u.id}: missing core metadata`);assert.ok(Array.isArray(u.vocabulary)&&u.vocabulary.length>=8,`${level} unit ${u.id}: vocabulary`);assert.ok(u.vocabulary.every(v=>Array.isArray(v)&&v.length===2&&v[0]&&v[1]),`${level} unit ${u.id}: bad vocabulary pair`);assert.ok(Array.isArray(u.sentences)&&u.sentences.length>=4,`${level} unit ${u.id}: sentences`);assert.ok(u.sentences.every(v=>Array.isArray(v)&&v.length===2&&v[0]&&v[1]),`${level} unit ${u.id}: bad sentence pair`);assert.ok(Array.isArray(u.dialogue)&&u.dialogue.length>=2,`${level} unit ${u.id}: dialogue`);assert.ok(Array.isArray(u.listening)&&u.listening.length>=4,`${level} unit ${u.id}: listening`);assert.ok(new Set(u.listening).size===u.listening.length,`${level} unit ${u.id}: duplicate listening item`);assert.ok(Array.isArray(u.speaking)&&u.speaking.length>=2,`${level} unit ${u.id}: speaking`);assert.ok(Array.isArray(u.exercises)&&u.exercises.length===4,`${level} unit ${u.id}: base exercise count`);assert.deepEqual(u.exercises.map(e=>e.type),['mcq','mcq','translate','build'],`${level} unit ${u.id}: base exercise order`);for(const e of u.exercises){assert.ok(e.q,`${level} unit ${u.id}: exercise question`);if(e.type==='mcq'){assert.ok(Array.isArray(e.options)&&e.options.length===4,`${level} unit ${u.id}: mcq options`);assert.ok(new Set(e.options).size===e.options.length,`${level} unit ${u.id}: duplicate mcq options`);assert.ok(Number.isInteger(e.answer)&&e.answer>=0&&e.answer<e.options.length,`${level} unit ${u.id}: mcq answer`)}if(e.type==='translate')assert.ok(typeof e.answer==='string'&&e.answer.length>0,`${level} unit ${u.id}: translate answer`);if(e.type==='build'){const parts=e.parts||e.words;assert.ok(Array.isArray(parts)&&parts.length>=2,`${level} unit ${u.id}: build parts`);assert.equal(tokens(parts.join(' ')),tokens(e.answer),`${level} unit ${u.id}: build token mismatch`)}}}return json}
const a1=validateCourse('content/a1-curriculum.json','A1');
const a2=validateCourse('content/a2-curriculum.json','A2');
const index=fs.readFileSync('index.html','utf8');for(const asset of ['content/content-loader.js','app.js','premium.js','premium-ui.js','manifest.json'])assert.ok(index.includes(asset),`index missing ${asset}`);
const loader=fs.readFileSync('content/content-loader.js','utf8');for(const token of ['speakio_level','a2-curriculum.json','course-system.js','EXERCISES_PER_UNIT=10','function expandExercises','data.units.forEach(expandExercises)'])assert.ok(loader.includes(token),`course loader contract missing: ${token}`);assert.equal((loader.match(/EXERCISES_PER_UNIT=10/g)||[]).length,1,'10-exercise target missing');
const course=fs.readFileSync('course-system.js','utf8');for(const token of ['speakio_course_progress_v2','speakio_level','switchLevel','A1','A2','B1','B2','C1','unlocked'])assert.ok(course.includes(token),`course progress contract missing: ${token}`);
const sw=fs.readFileSync('sw.js','utf8');for(const asset of ['./index.html','./app.js','./runtime-fixes.js','./build-fix.js','./course-system.js','./premium.js','./premium-ui.js','./manifest.json','./content/a1-curriculum.json','./content/a2-curriculum.json','./content/content-loader.js'])assert.ok(sw.includes(asset),`SW missing ${asset}`);
const manifest=JSON.parse(fs.readFileSync('manifest.json','utf8'));assert.equal(manifest.short_name,'Speakio');assert.equal(manifest.display,'standalone');assert.ok(Array.isArray(manifest.icons)&&manifest.icons.length>0);
const coach=fs.readFileSync('api/coach.js','utf8');assert.ok(coach.includes('AI_API_URL')&&coach.includes('AI_API_KEY')&&coach.includes('AI_MODEL'));
const premium=fs.readFileSync('premium.js','utf8');assert.ok(premium.includes('speakio_premium_v2')&&premium.includes('SpeakioPremium')&&premium.includes('activateLocal'));
const pui=fs.readFileSync('premium-ui.js','utf8');assert.ok(pui.includes('SpeakioPremium')&&pui.includes('premium-card'));
console.log(`Speakio QA OK — A1 ${a1.units.length} + A2 ${a2.units.length} units, 10 runtime exercises per unit (${(a1.units.length+a2.units.length)*10} effective exercises), multi-level state, progression locks, PWA, AI coach and premium contracts validated.`);