(function(){
'use strict';
var KEY='speakio_state_v3';
function read(){try{return JSON.parse(localStorage.getItem(KEY)||'null');}catch(e){return null;}}
function write(s){localStorage.setItem(KEY,JSON.stringify(s));}
function today(){var d=new Date();return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0');}
function norm(s){return String(s==null?'':s).toLowerCase().trim().replace(/[.,!?;:'"“”‘’]/g,'').replace(/\s+/g,' ');}
function toast(t){var e=document.querySelector('#toast');if(e){e.textContent=t;e.classList.add('show');setTimeout(function(){e.classList.remove('show');},1700);}}
function units(){return typeof window.getSpeakioUnits==='function'?window.getSpeakioUnits():[];}
function unit(id){return units().find(function(x){return Number(x.id)===Number(id);});}
function state(){var s=read();if(!s)return null;s.completed=Array.from(new Set((s.completed||[]).map(Number)));s.savedWords=Array.from(new Set(s.savedWords||[]));s.knownWords=Array.from(new Set(s.knownWords||[]));s.mistakes=(s.mistakes||[]).slice(-50);s.daily=s.daily&&s.daily.date===today()?s.daily:{date:today(),done:0,listening:0,speaking:0};s.daily.done=Number(s.daily.done||0);s.daily.listening=Number(s.daily.listening||0);s.daily.speaking=Number(s.daily.speaking||0);s.voiceStats=s.voiceStats||{attempts:0,average:0};s.lastStudyDate=s.lastStudyDate||'';write(s);return s;}
try{
var initial=state();
if(!window.SpeechRecognition&&!window.webkitSpeechRecognition)document.documentElement.dataset.voiceSupport='false';
var replay=false,currentLesson=0,exerciseIndex=0,sessionScore=0,sessionTotal=0,buildWords=[];
function markStudy(s){var now=today(),last=s.lastStudyDate||'';if(last===now)return;if(!last)s.streak=Math.max(1,Number(s.streak||0));else{var a=new Date(last+'T00:00:00'),b=new Date(now+'T00:00:00'),days=Math.round((b-a)/86400000);s.streak=days===1?Number(s.streak||0)+1:1;}s.lastStudyDate=now;}
function exercise(){var u=unit(currentLesson),a=u&&u.exercises||[];return a.length?a[exerciseIndex%a.length]:null;}
function answerText(z){if(z&&Array.isArray(z.options)&&Number.isInteger(z.answer))return z.options[z.answer];return z&&z.answer||'';}
function keyFor(z){return currentLesson+'|'+norm(z&&z.q||z&&z.question||z&&z.prompt||'');}
function schedule(z,correct){var s=state();if(!s||!z)return;var key=keyFor(z),idx=(s.mistakes||[]).findIndex(function(m){return m.key===key;});if(correct){if(idx>=0){var m=s.mistakes[idx],reps=Number(m.reps||0)+1,steps=[1,3,7,14,30],days=steps[Math.min(reps-1,steps.length-1)];m.reps=reps;m.interval=days;m.dueAt=new Date(Date.now()+days*86400000).toISOString();m.lastResult='correct';write(s);}}else{var item=idx>=0?s.mistakes[idx]:{key:key,unitId:currentLesson,question:z.q||z.question||z.prompt||'',answer:answerText(z),reps:0,interval:10};item.dueAt=new Date(Date.now()+10*60000).toISOString();item.lastResult='wrong';if(idx<0)s.mistakes.push(item);else s.mistakes[idx]=item;s.mistakes=s.mistakes.slice(-50);write(s);}}
var originalStart=window.Speakio&&window.Speakio.startLesson;
var originalNext=window.Speakio&&window.Speakio.next;
var originalGo=window.Speakio&&window.Speakio.go;
if(originalStart){window.Speakio.startLesson=function(id){var s=state();replay=!!(s&&s.completed&&s.completed.includes(Number(id)));currentLesson=Number(id);exerciseIndex=0;sessionScore=0;sessionTotal=(unit(id)&&unit(id).exercises||[]).length;buildWords=[];originalStart(id);setTimeout(function(){if(replay){var box=document.querySelector('.lessonbox');if(box&&!box.querySelector('.replay-hint')){var p=document.createElement('div');p.className='hint replay-hint';p.innerHTML='🔁 <b>Tekrar modu:</b> Bu ders XP ve günlük hedefi yeniden saymaz.';box.appendChild(p);}}},30);};}
if(originalNext){window.Speakio.next=function(){var before=state(),oldDaily=before?Number(before.daily.done||0):0,wasReplay=replay;originalNext();var after=state();if(!after)return;after.daily=after.daily||{date:today(),done:0,listening:0,speaking:0};if(wasReplay){after.daily.done=Math.max(0,Number(after.daily.done||0)-1);after.xp=Math.max(0,Number(after.xp||0)-25);replay=false;write(after);toast('Tekrar tamamlandı • XP korunuyor');}else if(Number(after.daily.done||0)>oldDaily){markStudy(after);write(after);}exerciseIndex++;};}
var originalAnswer=window.Speakio&&window.Speakio.answer;
if(originalAnswer){window.Speakio.answer=function(i){var z=exercise(),buttons=Array.prototype.slice.call(document.querySelectorAll('.lessonbox .answer')),correct=z&&Number(i)===Number(z.answer);if(!z||!buttons.length){originalAnswer(i);return;}if(correct)sessionScore++;schedule(z,correct);buttons.forEach(function(b,j){b.disabled=true;if(j===Number(z.answer))b.classList.add('selected');if(j===Number(i)&&!correct)b.classList.add('wrong');});toast(correct?'Doğru! 🎉':'Tekrar edeceğiz 💪');setTimeout(function(){window.Speakio.next();},350);};}
var originalText=window.Speakio&&window.Speakio.checkText;
if(originalText){window.Speakio.checkText=function(){var z=exercise(),v=document.querySelector('#answer');v=v?v.value:'';if(!z){originalText();return;}var answers=Array.isArray(z.answers)?z.answers:[z.answer],correct=answers.some(function(a){return norm(a)===norm(v);});if(correct)sessionScore++;schedule(z,correct);toast(correct?'Doğru! 🎉':'Cevabı tekrar et 💪');setTimeout(function(){window.Speakio.next();},350);};}
var originalAdd=window.Speakio&&window.Speakio.addWord;
if(originalAdd){window.Speakio.addWord=function(i){var z=exercise(),parts=z&&(z.parts||z.words)||[],b=Array.prototype.slice.call(document.querySelectorAll('.lessonbox .answer'))[i];if(!b||parts[i]==null)return;buildWords.push(parts[i]);b.disabled=true;b.style.opacity='.45';var h=document.querySelector('.lessonbox .hint');if(h)h.textContent=buildWords.join(' ');};}
var originalBuild=window.Speakio&&window.Speakio.checkBuild;
if(originalBuild){window.Speakio.checkBuild=function(){var z=exercise(),correct=!!z&&norm(buildWords.join(' '))===norm(z.answer||'');if(correct)sessionScore++;if(z)schedule(z,correct);toast(correct?'Doğru! 🎉':'Cümleyi tekrar deneyeceğiz 💪');buildWords=[];setTimeout(function(){window.Speakio.next();},350);};}
var originalListen=window.Speakio&&window.Speakio.listenAnswer;
if(originalListen){window.Speakio.listenAnswer=function(i){var choices=Array.prototype.slice.call(document.querySelectorAll('.listen .choice')).map(function(x){return x.textContent.trim();});var audio=document.querySelector('.listen .audio'),attr=audio?audio.getAttribute('onclick'):'',m=attr&&attr.match(/say\('([\s\S]*)'\)/),correct=m?m[1].replace(/&#39;/g,"'"):'';if(!choices.length||!correct){originalListen(i);return;}var s=state();if(norm(choices[i])===norm(correct)){s.listeningDone=Number(s.listeningDone||0)+1;s.xp=Number(s.xp||0)+10;s.daily.listening=1;markStudy(s);write(s);toast('+10 XP • Dinleme doğru! 🎧');}else toast('Bir kez daha dinle 🎧');setTimeout(function(){window.Speakio.go('listen');},500);};}
if(originalGo){window.Speakio.go=function(v){originalGo(v);setTimeout(function(){if(v==='review')reviewMeta();if(v==='home')homeTasks();if(v==='settings')settingsTools();},0);};}
function reviewMeta(){var root=document.querySelector('main section'),s=state();if(!root||!s)return;var old=root.querySelector('.review-meta');if(old)old.remove();var now=Date.now(),all=s.mistakes||[],due=all.filter(function(m){return !m.dueAt||Date.parse(m.dueAt)<=now;});var card=document.createElement('div');card.className='card review-meta';card.innerHTML='<b>⏱️ Akıllı tekrar planı</b><p class="muted">'+due.length+' soru şimdi hazır • '+Math.max(0,all.length-due.length)+' soru bekliyor.</p><small class="muted">Yanlışlar 10 dk sonra; başarılı tekrarlar 1 → 3 → 7 → 14 → 30 gün aralıklarla planlanır.</small>';root.insertBefore(card,root.children[1]||null);}
function homeTasks(){var root=document.querySelector('main section'),s=state();if(!root||!s)return;var old=root.querySelector('.daily-tasks');if(old)old.remove();var d=s.daily,count=Math.min(3,(d.done?1:0)+(d.listening?1:0)+(d.speaking?1:0)),box=document.createElement('div');box.className='card daily-tasks';box.innerHTML='<div class="row"><b>⚡ Bugünün mini görevleri</b><span>'+count+'/3</span></div><p class="muted">Dersi tamamla · 1 dinleme · 1 konuşma</p><div class="taskline"><span>'+(d.done?'✓':'○')+' Ders</span><span>'+(d.listening?'✓':'○')+' Dinleme</span><span>'+(d.speaking?'✓':'○')+' Konuşma</span></div>';root.insertBefore(box,root.querySelector('.section')||root.firstChild);}
function settingsTools(){var root=document.querySelector('main section'),s=state();if(!root||!s||root.querySelector('.data-tools'))return;var box=document.createElement('div');box.className='card data-tools';box.innerHTML='<b>🔐 Verilerin</b><p class="muted">İlerleme bilgilerin bu cihazda tutulur. Yedek alabilir veya geri yükleyebilirsin.</p><div class="grid"><button class="secondary" id="speakioExport">Dışa aktar</button><button class="secondary" id="speakioImportBtn">İçe aktar</button></div><input id="speakioImport" type="file" accept="application/json" hidden>';root.appendChild(box);box.querySelector('#speakioExport').onclick=function(){var blob=new Blob([JSON.stringify(state(),null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='speakio-progress.json';a.click();setTimeout(function(){URL.revokeObjectURL(a.href);},1000);};box.querySelector('#speakioImportBtn').onclick=function(){box.querySelector('#speakioImport').click();};box.querySelector('#speakioImport').onchange=function(e){var f=e.target.files&&e.target.files[0];if(!f)return;var r=new FileReader();r.onload=function(){try{var incoming=JSON.parse(r.result);if(!incoming||typeof incoming!=='object'||!Array.isArray(incoming.completed))throw new Error('invalid');localStorage.setItem(KEY,JSON.stringify(Object.assign({},state(),incoming)));location.reload();}catch(err){toast('Geçersiz Speakio yedeği');}};r.readAsText(f);};}
var originalVoice=window.Speakio&&window.Speakio.listenSpeech;
if(originalVoice){window.Speakio.listenSpeech=function(){var R=window.SpeechRecognition||window.webkitSpeechRecognition;if(!R){originalVoice();return;}var s=state(),bubble=document.querySelector('.practice .bubble'),prompt=bubble?bubble.textContent:'',r=new R(),mic=document.querySelector('#mic');r.lang='en-US';r.interimResults=false;r.maxAlternatives=1;r.onstart=function(){if(mic)mic.classList.add('listening');};r.onend=function(){if(mic)mic.classList.remove('listening');};r.onerror=function(){toast('Mikrofon iznini kontrol et.');};r.onresult=function(e){var text=e.results[0][0].transcript||'',p=norm(prompt).split(' ').filter(Boolean),w=norm(text).split(' ').filter(Boolean),uniq=Array.from(new Set(p)),hit=uniq.filter(function(x){return w.indexOf(x)>=0;}).length,coverage=uniq.length?hit/uniq.length:0,length=Math.min(1,w.length/8),score=Math.round((coverage*.7+length*.3)*100);s.conversations=Number(s.conversations||0)+1;s.daily.speaking=1;s.voiceStats=s.voiceStats||{attempts:0,average:0};s.voiceStats.average=Math.round((s.voiceStats.average*s.voiceStats.attempts+score)/(s.voiceStats.attempts+1));s.voiceStats.attempts++;if(score>=70)s.xp=Number(s.xp||0)+5;markStudy(s);write(s);voiceResult(text,score);};r.start();};}
function voiceResult(text,score){var sec=document.querySelector('main section');if(!sec)return;var old=sec.querySelector('.voice-result');if(old)old.remove();var box=document.createElement('div');box.className='card voice-result';var label=score>=85?'Mükemmel! 🏆':score>=70?'Çok iyi! 🎉':score>=50?'İyi gidiyorsun 💪':'Bir kez daha deneyelim 🎯';box.innerHTML='<b>'+label+'</b><div class="progress"><i style="width:'+score+'%"></i></div><p><strong>'+score+'/100</strong> konuşma skoru</p><p class="muted">Söylediğin: “'+String(text).replace(/[&<>"']/g,'')+'”</p><small class="muted">'+(score>=70?'Ana fikre bir ayrıntı daha ekle.':'Görevdeki ana kelimeleri kullan ve cümleyi biraz uzat.')+'</small>';sec.appendChild(box);window.scrollTo({top:document.body.scrollHeight,behavior:'smooth'});}
}catch(e){console.warn('Speakio runtime hardening skipped',e);}
})();