(()=>{'use strict';
const KEY='speakio_state_v3';const read=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'null')}catch{return null}};const write=s=>localStorage.setItem(KEY,JSON.stringify(s));const today=()=>new Date().toISOString().slice(0,10);const norm=s=>String(s??'').toLowerCase().trim().replace(/[^a-z0-9ğüşıöçâîû]+/gi,' ').replace(/\s+/g,' ');const esc=s=>String(s??'').replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[m]));const toast=t=>{const e=document.querySelector('#toast');if(e){e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),1700)}};
try{
 let s=read();if(s){s.completed=[...new Set((s.completed||[]).map(Number).filter(Number.isFinite))];s.savedWords=[...new Set(s.savedWords||[])];s.knownWords=[...new Set(s.knownWords||[])];s.mistakes=(s.mistakes||[]).slice(-30);s.review=s.review&&typeof s.review==='object'?s.review:{};s.daily=s.daily&&typeof s.daily==='object'?s.daily:{date:'',done:0};if(typeof s.daily.done!=='number')s.daily.done=0;s.lastStudyDate=s.lastStudyDate||'';s.voiceStats=s.voiceStats||{attempts:0,average:0};write(s)}
 if(!window.SpeechRecognition&&!window.webkitSpeechRecognition)document.documentElement.dataset.voiceSupport='false';
 let replay=false,sessionScore=0,sessionTotal=0,currentLesson=0,buildFix=[];
 const curriculum=()=>typeof getSpeakioUnits==='function'?getSpeakioUnits():[];
 const currentExercise=()=>{const h=document.querySelector('.lessonbox h2')?.textContent?.trim()||'';let best=null;for(const u of curriculum()){for(const z of u.exercises||[]){const q=z.q||z.question||z.prompt||'';if(norm(q)===norm(h)||norm(z.prompt||'')===norm(h)){best={u,z};break} }if(best)break}return best?.z||null};
 const originalStart=window.Speakio?.startLesson,originalNext=window.Speakio?.next,originalGo=window.Speakio?.go;
 if(originalStart)window.Speakio.startLesson=function(id){const st=read();replay=!!st?.completed?.includes(Number(id));currentLesson=Number(id);sessionScore=0;sessionTotal=0;buildFix=[];originalStart(id);setTimeout(()=>{sessionTotal=Number(document.querySelector('.lessonMeta')?.textContent?.match(/\/(\d+)/)?.[1]||0);if(replay){const el=document.querySelector('.lessonbox');if(el){const p=document.createElement('div');p.className='hint';p.innerHTML='🔁 <b>Tekrar modu:</b> Bu ders XP ve günlük hedefi yeniden saymaz.';el.appendChild(p)}}},0)};
 if(originalNext)window.Speakio.next=function(){const before=read(),wasReplay=replay,oldDaily=Number(before?.daily?.done||0),oldXp=Number(before?.xp||0),oldStreak=Number(before?.streak||0);originalNext();const after=read();if(!after)return;if(wasReplay){after.daily=after.daily||{date:today(),done:0};after.daily.done=Math.max(0,Number(after.daily.done||0)-1);after.xp=Math.max(0,Number(after.xp||0)-25);write(after);replay=false;toast('Tekrar tamamlandı • XP hedefi korunuyor')}else if(Number(after.daily?.done||0)>oldDaily){const now=today(),last=after.lastStudyDate;if(last!==now){if(last){const days=Math.round((new Date(now+'T00:00:00')-new Date(last+'T00:00:00'))/86400000);after.streak=days===1?Math.max(1,oldStreak+1):1}else after.streak=Math.max(1,oldStreak||1);after.lastStudyDate=now;write(after)}}setTimeout(()=>{if(document.querySelector('.resultHero')){const card=document.querySelector('.resultHero')?.parentElement?.querySelector('.card');if(card){const total=sessionTotal||Number((document.querySelector('.lessonMeta')?.textContent||'').match(/\/(\d+)/)?.[1]||0);const pct=total?Math.round(sessionScore/total*100):0;card.innerHTML=`<b>${sessionScore}/${total} doğru</b><div class="progress"><i style="width:${pct}%"></i></div>`}}},0)};
 const originalAnswer=window.Speakio?.answer;
 if(originalAnswer)window.Speakio.answer=function(i){const z=currentExercise();const opts=[...document.querySelectorAll('.lessonbox .answer')].map(x=>x.textContent.trim());if(!z||!opts.length){originalAnswer(i);return}let correct=false;if(typeof z.answer==='number')correct=Number(i)===Number(z.answer);else if(Array.isArray(z.options))correct=norm(opts[i])===norm(z.options[Number(z.answer)]);else correct=norm(opts[i])===norm(z.answer);if(correct)sessionScore++;if(!correct){const st=read();st.mistakes=[...(st.mistakes||[]),{unitId:currentLesson,question:z.q||z.question||'',answer:Array.isArray(z.options)&&typeof z.answer==='number'?z.options[z.answer]:String(z.answer||''),dueAt:new Date(Date.now()+10*60*1000).toISOString(),interval:10,reps:0}].slice(-30);write(st)}opts.forEach((_,j)=>{const b=document.querySelectorAll('.lessonbox .answer')[j];if(b){b.disabled=true;if(j===Number(z.answer))b.classList.add('selected');if(j===i&&!correct)b.classList.add('wrong')}});toast(correct?'Doğru! 🎉':'Tekrar edeceğiz 💪');setTimeout(()=>window.Speakio.next(),350)};
 const originalText=window.Speakio?.checkText;
 if(originalText)window.Speakio.checkText=function(){const z=currentExercise(),v=document.querySelector('#answer')?.value||'';if(!z){originalText();return}const answers=Array.isArray(z.answers)?z.answers:[z.answer];const correct=answers.some(x=>norm(x)===norm(v));if(correct)sessionScore++;if(!correct){const st=read();st.mistakes=[...(st.mistakes||[]),{unitId:currentLesson,question:z.q||z.question||'',answer:String(z.answer||''),dueAt:new Date(Date.now()+10*60*1000).toISOString(),interval:10,reps:0}].slice(-30);write(st)}toast(correct?'Doğru! 🎉':'Cevabı tekrar et 💪');setTimeout(()=>window.Speakio.next(),350)};
 const originalAdd=window.Speakio?.addWord,originalBuild=window.Speakio?.checkBuild;
 if(originalAdd)window.Speakio.addWord=function(i){const b=[...document.querySelectorAll('.lessonbox .answer')][i];if(!b)return;buildFix.push(b.textContent.trim());const h=document.querySelector('.lessonbox .hint');if(h)h.textContent=buildFix.join(' ');b.disabled=true;b.style.opacity='.45'};
 if(originalBuild)window.Speakio.checkBuild=function(){const z=currentExercise(),target=norm(z?.answer||'');const got=norm(buildFix.join(' '));if(!z){originalBuild();return}const correct=got===target;if(correct)sessionScore++;if(!correct){const st=read();st.mistakes=[...(st.mistakes||[]),{unitId:currentLesson,question:z.q||z.question||'',answer:String(z.answer||''),dueAt:new Date(Date.now()+10*60*1000).toISOString(),interval:10,reps:0}].slice(-30);write(st)}toast(correct?'Doğru! 🎉':'Cümleyi tekrar deneyeceğiz 💪');buildFix=[];setTimeout(()=>window.Speakio.next(),350)};
 const originalListen=window.Speakio?.listenAnswer;if(originalListen)window.Speakio.listenAnswer=function(i){const choices=[...document.querySelectorAll('.listen .choice')].map(x=>x.textContent.trim()),audio=document.querySelector('.listen .audio'),attr=audio?.getAttribute('onclick')||'',m=attr.match(/say\('([\\s\\S]*)'\)/),correct=m?m[1].replace(/&#39;/g,"'"):'';if(!choices.length||!correct){originalListen(i);return}const st=read();if(norm(choices[i])===norm(correct)){st.listeningDone=Number(st.listeningDone||0)+1;st.xp=Number(st.xp||0)+10;write(st);toast('+10 XP • Dinleme doğru! 🎧')}else toast('Bir kez daha dinle 🎧');setTimeout(()=>window.Speakio.go('listen'),500)};
 if(originalGo)window.Speakio.go=function(v){originalGo(v);if(v==='review')setTimeout(renderReviewMeta,0)};
 function renderReviewMeta(){const root=document.querySelector('main section'),st=read();if(!root||!st)return;root.querySelector('.review-meta')?.remove();const now=Date.now(),due=(st.mistakes||[]).filter(m=>!m.dueAt||Date.parse(m.dueAt)<=now).length,all=(st.mistakes||[]).length,card=document.createElement('div');card.className='card review-meta';card.innerHTML=`<b>⏱️ Akıllı tekrar planı</b><p class="muted">${due} soru şimdi hazır • ${Math.max(0,all-due)} soru sonraki tekrarını bekliyor.</p>`;root.insertBefore(card,root.children[1]||null)}
 const originalVoice=window.Speakio?.listenSpeech;if(originalVoice)window.Speakio.listenSpeech=function(){const R=window.SpeechRecognition||window.webkitSpeechRecognition;if(!R){originalVoice();return}const st=read(),prompt=document.querySelector('.practice .bubble')?.textContent||'',r=new R();r.lang='en-US';r.interimResults=false;r.maxAlternatives=1;const mic=document.querySelector('#mic');r.onstart=()=>mic?.classList.add('listening');r.onend=()=>mic?.classList.remove('listening');r.onerror=()=>toast('Mikrofon iznini kontrol et.');r.onresult=async e=>{const text=e.results[0][0].transcript||'',p=norm(prompt).split(' ').filter(Boolean),w=norm(text).split(' ').filter(Boolean),uniq=[...new Set(p)],hit=uniq.filter(x=>w.includes(x)).length,coverage=uniq.length?hit/uniq.length:0,length=Math.min(1,w.length/8),score=Math.round((coverage*.7+length*.3)*100);st.conversations=Number(st.conversations||0)+1;st.voiceStats=st.voiceStats||{attempts:0,average:0};st.voiceStats.average=Math.round(((st.voiceStats.average*st.voiceStats.attempts)+score)/(st.voiceStats.attempts+1));st.voiceStats.attempts++;if(score>=70)st.xp=Number(st.xp||0)+5;write(st);renderVoiceResult(text,score,'');try{const ai=await fetch('/api/coach',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({prompt,transcript:text,level:'A1'})});if(ai.ok){const data=await ai.json();if(data?.text)renderVoiceResult(text,score,data.text)}}catch{}};r.start()};
 function renderVoiceResult(text,score,ai){const sec=document.querySelector('main section');if(!sec)return;sec.querySelector('.voice-result')?.remove();const box=document.createElement('div');box.className='card voice-result';const label=score>=85?'Mükemmel! 🏆':score>=70?'Çok iyi! 🎉':score>=50?'İyi gidiyorsun 💪':'Bir kez daha deneyelim 🎯';box.innerHTML=`<b>${label}</b><div class="progress"><i style="width:${score}%"></i></div><p><strong>${score}/100</strong> konuşma skoru</p><p class="muted">Söylediğin: “${esc(text)}”</p>${ai?`<div class="hint"><b>🤖 Speakio Coach</b><br>${esc(ai).replace(/\n/g,'<br>')}</div>`:`<small class="muted">${score>=70?'Aynı fikre bir ayrıntı daha ekle.':'Görevdeki ana kelimeleri kullan ve cümleyi biraz uzat.'}</small>`}`;sec.appendChild(box);window.scrollTo({top:document.body.scrollHeight,behavior:'smooth'})}
}catch(e){console.warn('Speakio runtime hardening skipped',e)}
})();